// <auto-generated />
namespace TCC_API_Locadora_Garagem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Build0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Build0001));
        
        string IMigrationMetadata.Id
        {
            get { return "201908261941347_Build0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
